"""initial schema

Revision ID: 9499407a2570
Revises: 
Create Date: 2026-02-25 03:11:22.904222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9499407a2570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.alter_column('usage_start',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True,
               existing_server_default=sa.text("'06:00'"))
        batch_op.alter_column('usage_end',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True,
               existing_server_default=sa.text("'22:00'"))
        batch_op.drop_column('hours')
        batch_op.drop_column('usage_time')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('capture_image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('capture_model_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('capture_model_path',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('capture_image_path',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_time', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('hours', sa.FLOAT(), nullable=True))
        batch_op.alter_column('usage_end',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'22:00'"))
        batch_op.alter_column('usage_start',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'06:00'"))

    # ### end Alembic commands ###
